name: Mason - The Pillars app generator
log:
  level: info
  format: classic
  output:
    type: console
api:
  enabled: true
  http:
    host: 0.0.0.0
    port: 8765
    logging:
      enabled: false
      headers: true
      body: true
      level: debug
  open-api:
    enabled: true
    path-prefix: ["docs"]
    yaml-name: "pillars-example.yaml"
    context-path: []
    use-relative-paths: true
    show-extensions: false
admin:
  enabled: true
  http:
    host: 0.0.0.0
    port: 18765
    logging:
      enabled: true
      headers: true
      body: true
      level: debug
  open-api:
    enabled: true
    path-prefix: ["docs"]
    yaml-name: "pillars-example.yaml"
    context-path: []
    use-relative-paths: true
    show-extensions: false
observability:
  enabled: false
  service-name: mason
  metrics:
    enabled: true
  traces:
    enabled: true
feature-flags:
  enabled: true
  flags:
    - name: feature-1
      status: enabled
    - name: feature-2
      status: disabled
http-client:
  follow-redirect: true
  user-agent: pillars/bookstore
  logging:
    enabled: true
    headers: true
    body: true
    level: info

# Mason configuration
owner: FunktionalIO
repository: pillars
refresh: PT1h
min-pillars-version: "0.4.0"
dependencies:
  scala: "3.6.3"
  iron: "2.6.0"
  tapir: "1.11.20"
  munit: "1.1.0"
  munit-ce: "2.0.0"
  observability:
    signoz: "0.76.2"
    otel-collector: "0.111.34"
    clickhouse: "24.1.2"
    zookeeper: "3.7.1"
